### ISSUE TITLE
Confirmation to modify and publish mpv-android?

### ISSUE THREAD

**Issue by ghulammohiuddin2398** [mpv-android/mpv-android#286]
As your Licence says that anyone can modify this software subject to include the licence in copies of software.
I was trying to rename the package but i always get this issue:

`java.lang.UnsatisfiedLinkError: No implementation found for void pk.xyz.mpv.MPVLib.create(android.content.Context) (tried Java_pk_xyz_mpv_MPVLib_create and Java_pk_xyz_mpv_MPVLib_create__Landroid_content_Context_2)
        at pk.xyz.mpv.MPVLib.create(Native Method)
        at pk.xyz.mpv.MPVView.initialize(MPVView.kt:18)
        at pk.xyz.mpv.MPVActivity.onCreate(MPVActivity.kt:182)
        at android.app.Activity.performCreate(Activity.java:7258)
        at android.app.Activity.performCreate(Activity.java:7249)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3150)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3307)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2036)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7081)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)`

Although the application build successfully and works fine but when is choose a file to play above error occurs and application crashes. Now if I rename the **pk** back to **is** this error vanishes and application works properly. Can you please tell what am i doing wrong? Moreover warn me if I'm misunderstanding your license.

**Comment by gmohiuddin215** [comment]
Just solved the issue but As I m new to licences so I want to confirm that Am i free to modify and publish mpv-android if I include the given Licence into my app as it is included in mpv-android or I have to write it in every file of project?

**Comment by ImOnii** [comment]
@gmohiuddin215
Hey how did you fix it, i’m having the same problem

**Comment by gitlzq** [comment]
I’m having the same problem ...
