### ISSUE TITLE
Need help with buildall.sh

### ISSUE THREAD

**Issue by Ajaja** [mpv-android/mpv-android#309]
I'm trying to follow the buildscripts instruction and build ```mpv-android``` using a clean Debian v10.5 amd64 install.
First step  ```./download.sh```  went well ( I only had to download OpenJDK and set JAVA_HOME ).
But on the next ```./buildall.sh``` step  I have a problem with building ```dav1d``` :
```
alex@virtdeb2:~/mpv-android/buildscripts$ ./buildall.sh --clean
Building mpv-android...
Dependencies: mpv
Building mpv...
Dependencies: ffmpeg libass lua
Building ffmpeg...
Dependencies: mbedtls dav1d
Building mbedtls...
Dependencies:
~/mpv-android/buildscripts/deps/mbedtls ~/mpv-android/buildscripts
  CC    aes.c
  CC    aesni.c
 .....
  CC    x509/cert_req.c
  CC    x509/cert_write.c
  CC    x509/crl_app.c
  CC    x509/req_app.c
  CC    psa/psa_constant_names.c
 armv7a-linux-androideabi21-clang common.o onefile.o fuzz_x509csr.o ../../tests/src/helpers.o ../../tests/src/random.o -L../../library -lmbedtls -lmbedx509 -lmbedcrypto  -o fuzz_x509csr
 armv7a-linux-androideabi21-clang common.o onefile.o fuzz_server.o ../../tests/src/helpers.o ../../tests/src/random.o -L../../library -lmbedtls -lmbedx509 -lmbedcrypto  -o fuzz_server
 armv7a-linux-androideabi21-clang common.o onefile.o fuzz_privkey.o ../../tests/src/helpers.o ../../tests/src/random.o -L../../library -lmbedtls -lmbedx509 -lmbedcrypto  -o fuzz_privkey
 armv7a-linux-androideabi21-clang common.o onefile.o fuzz_x509crt.o ../../tests/src/helpers.o ../../tests/src/random.o -L../../library -lmbedtls -lmbedx509 -lmbedcrypto  -o fuzz_x509crt
 armv7a-linux-androideabi21-clang common.o onefile.o fuzz_dtlsclient.o ../../tests/src/helpers.o ../../tests/src/random.o -L../../library -lmbedtls -lmbedx509 -lmbedcrypto  -o fuzz_dtlsclient
 armv7a-linux-androideabi21-clang common.o onefile.o fuzz_pubkey.o ../../tests/src/helpers.o ../../tests/src/random.o -L../../library -lmbedtls -lmbedx509 -lmbedcrypto  -o fuzz_pubkey
 armv7a-linux-androideabi21-clang common.o onefile.o fuzz_x509crl.o ../../tests/src/helpers.o ../../tests/src/random.o -L../../library -lmbedtls -lmbedx509 -lmbedcrypto  -o fuzz_x509crl
 armv7a-linux-androideabi21-clang common.o onefile.o fuzz_client.o ../../tests/src/helpers.o ../../tests/src/random.o -L../../library -lmbedtls -lmbedx509 -lmbedcrypto  -o fuzz_client
 armv7a-linux-androideabi21-clang common.o onefile.o fuzz_dtlsserver.o ../../tests/src/helpers.o ../../tests/src/random.o -L../../library -lmbedtls -lmbedx509 -lmbedcrypto  -o fuzz_dtlsserver
~/mpv-android/buildscripts
Building dav1d...
Dependencies:
~/mpv-android/buildscripts/deps/dav1d ~/mpv-android/buildscripts
The Meson build system
Version: 0.49.2
Source dir: /home/alex/mpv-android/buildscripts/deps/dav1d
Build dir: /home/alex/mpv-android/buildscripts/deps/dav1d/_build
Build type: cross build
Project name: dav1d
Project version: 0.7.1

meson.build:25:0: ERROR:  Compiler clang can not compile programs.

A full log can be found at /home/alex/mpv-android/buildscripts/deps/dav1d/_build/meson-logs/meson-log.txt

```

meson-log.txt is here:
```
Build started at 2020-09-14T16:55:18.308660
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.49.2
Source dir: /home/alex/mpv-android/buildscripts/deps/dav1d
Build dir: /home/alex/mpv-android/buildscripts/deps/dav1d/_build
Build type: cross build
Project name: dav1d
Project version: 0.7.1
Sanity testing C compiler: clang
Is cross compiler: False.
Sanity check compiler command line: clang /home/alex/mpv-android/buildscripts/deps/dav1d/_build/meson-private/sanitycheckc.c -o /home/alex/mpv-android/buildscripts/deps/dav1d/_build/meson-private/sanitycheckc.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:
/home/alex/mpv-android/buildscripts/sdk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot open crt1.o: No such file or directory
/home/alex/mpv-android/buildscripts/sdk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot open crti.o: No such file or directory
/home/alex/mpv-android/buildscripts/sdk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot open crtend.o: No such file or directory
/home/alex/mpv-android/buildscripts/sdk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot open crtn.o: No such file or directory
/home/alex/mpv-android/buildscripts/sdk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot find -lcompiler_rt-extras
/home/alex/mpv-android/buildscripts/sdk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot find -lgcc_s
/home/alex/mpv-android/buildscripts/sdk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot find -lc
/home/alex/mpv-android/buildscripts/sdk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot find -lcompiler_rt-extras
/home/alex/mpv-android/buildscripts/sdk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot find -lgcc_s
/home/alex/mpv-android/buildscripts/sdk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/crtbegin.o(.text+0xa): error: undefined reference to '__TMC_END__'
/home/alex/mpv-android/buildscripts/sdk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/crtbegin.o(.text+0x36): error: undefined reference to '__TMC_END__'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

-----

meson.build:25:0: ERROR:  Compiler clang can not compile programs.
```

Any suggestions?

**Comment by sfan5** [comment]
Looks like meson is somehow picking up android stuff as <i>host</i> compiler.

Do you have gcc installed? If not, try installing it.

**Comment by Ajaja** [comment]
I did try to install build-essential.
Yes, it builds  ```dav1d``` but installs everything into Debian's default /usr/local/....  folder.
On the next step pkg-config is unable to find this ```dav1d```.
Honestly, It was a first problem with ```bildall.sh``` I faced.. Then I realised that it uses wrong compiler, not from buildscripts/sdk, uninstalled build-essential,  tried again and got this problem with compiling ```dav1d```.

**Comment by sfan5** [comment]
You do need gcc.

> Yes, it builds dav1d but installs everything into Debian's default /usr/local/.... folder.

That's not supposed to happen.
The scripts configure a prefix path in `.../buildscripts/deps/dav1d/_build/crossfile.txt`, what does that file contain on your end?

**Comment by Ajaja** [comment]
crossfile.txt :
```
[binaries]
c = 'armv7a-linux-androideabi21-clang'
ar = 'arm-linux-androideabi-ar'
strip = 'arm-linux-androideabi-strip'
[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'armv7a'
endian = 'little'
[paths]
prefix = '/home/alex/mpv-android/buildscripts/prefix/armv7l'
```

I'v installed build-essential again. 
Result  (ran without root):
```
alex@virtdeb2:~/mpv-android/buildscripts$ ./buildall.sh --clean
Building mpv-android...
Dependencies: mpv
Building mpv...
Dependencies: ffmpeg libass lua
Building ffmpeg...
Dependencies: mbedtls dav1d
Building mbedtls...
Dependencies:
~/mpv-android/buildscripts/deps/mbedtls ~/mpv-android/buildscripts
  CC    aes.c
  CC    arc4.c
...
 armv7a-linux-androideabi21-clang common.o onefile.o fuzz_dtlsserver.o ../../tests/src/helpers.o ../../tests/src/random.o -L../../library -lmbedtls -lmbedx509 -lmbedcrypto  -o fuzz_dtlsserver
~/mpv-android/buildscripts
Building dav1d...
Dependencies:
~/mpv-android/buildscripts/deps/dav1d ~/mpv-android/buildscripts
The Meson build system
Version: 0.49.2
Source dir: /home/alex/mpv-android/buildscripts/deps/dav1d
Build dir: /home/alex/mpv-android/buildscripts/deps/dav1d/_build
Build type: cross build
Project name: dav1d
Project version: 0.7.1
Native C compiler: cc (gcc 8.3.0 "cc (Debian 8.3.0-6) 8.3.0")
Cross C compiler: armv7a-linux-androideabi21-clang (clang 9.0.8)
Host machine cpu family: arm
Host machine cpu: armv7a
Target machine cpu family: arm
Target machine cpu: armv7a
Build machine cpu family: x86_64
Build machine cpu: x86_64
Cross dependency threads found: YES
Checking for function "clock_gettime" : YES
Library dl found: YES
Checking for function "dlsym" with dependency -ldl: YES
Check usable header "stdatomic.h" : YES
Check usable header "unistd.h" : YES
Check usable header "io.h" : NO
Checking for function "getopt_long" : YES
Checking for function "_aligned_malloc" : NO
Checking for function "posix_memalign" : YES
Checking for function "getauxval" : YES
Checking for function "elf_aux_info" : NO
Compiler for C supports arguments -fvisibility=hidden: YES
Compiler for C supports arguments -Wundef: YES
Compiler for C supports arguments -Werror=vla: YES
Compiler for C supports arguments -Wno-maybe-uninitialized: NO
Compiler for C supports arguments -Wno-missing-field-initializers: YES
Compiler for C supports arguments -Wno-unused-parameter: YES
Compiler for C supports arguments -Werror=missing-prototypes: YES
Compiler for C supports arguments -Wshorten-64-to-32: YES
Compiler for C supports arguments -fomit-frame-pointer: YES
Compiler for C supports arguments -ffast-math: YES
Configuring config.h using configuration
Configuring version.h using configuration
Program doxygen found: NO
Program dot found: NO
Configuring cli_config.h using configuration
Library m found: YES
Compiler for C supports arguments -Werror=c11-extensions: YES
First supported argument: -Werror=c11-extensions
Program objcopy found: YES (/usr/bin/objcopy)
Checking for function "posix_memalign" : YES
Build targets in project: 27
Found ninja-1.8.2 at /usr/bin/ninja
ninja: Entering directory `_build'
[72/124] Compiling C object 'tools/f9d35d4@@dav1d_input@sta/input_ivf.c.o'.
../tools/input/ivf.c:94:9: warning: implicit declaration of function 'fseeko' is invalid in C99 [-Wimplicit-function-declaration]
        fseeko(c->f, rl32(data) + 8, SEEK_CUR);
       ^
...
5 warnings generated.
[100/124] Compiling C object 'tests/libfuzzer/68ecb3a@@dav1d_fuzzer@exe/main.c.o'.
../tests/libfuzzer/main.c:62:9: warning: implicit declaration of function 'fseeko' is invalid in C99 [-Wimplicit-function-declaration]
    if (fseeko(f, 0, SEEK_END) == -1) {
        ^
../tests/libfuzzer/main.c:67:18: warning: implicit declaration of function 'ftello' is invalid in C99 [-Wimplicit-function-declaration]
    if ((fsize = ftello(f)) == -1) {
                 ^
2 warnings generated.
[117/124] Compiling C object 'tests/libfuzzer/68ecb3a@@dav1d_fuzzer_mt@exe/main.c.o'.
../tests/libfuzzer/main.c:62:9: warning: implicit declaration of function 'fseeko' is invalid in C99 [-Wimplicit-function-declaration]
    if (fseeko(f, 0, SEEK_END) == -1) {
        ^
../tests/libfuzzer/main.c:67:18: warning: implicit declaration of function 'ftello' is invalid in C99 [-Wimplicit-function-declaration]
    if ((fsize = ftello(f)) == -1) {
                 ^
2 warnings generated.
[124/124] Linking target tests/picture.h_test.
ninja: Entering directory `_build'
[1/2] Installing files.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 112, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 504, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 341, in do_install
    self.install_targets(d)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 436, in install_targets
    d.dirmaker.makedirs(outdir, exist_ok=True)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 55, in makedirs
    os.makedirs(path, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/x86_64-linux-gnu'
FAILED: meson-install
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.

```

**Comment by sfan5** [comment]
I can only say "works for me", I have meson 0.55.1 on my system.
You could try updating yours I guess. (travis installs via `sudo pip3 install meson`)

**Comment by Ajaja** [comment]
> I have meson 0.55.1

Thank you!  
I removed meson installed by apt-get (it was v0.49.x) and installed meson using pip. 
Look like this problem is solved now and I was able to build apk.
