### ISSUE TITLE
lavfi cropdetect filter missing

### ISSUE THREAD

**Issue by Ashyni** [mpv-android/mpv-android#313]
Hi, i'm working on an lua script to do real time crop, and wanted to test it on android, but the filter `cropdetect` is not present.

Full list of lavfi filters:
https://pastebin.com/dpctYR9R

His there any limitation or specific reason ?

**Comment by Ashyni** [comment]
Hey, so just for testing, i have a build mpv-android with the gpl filters and it's working great.

Change made to:
https://github.com/mpv-android/mpv-android/blob/133a154ff7a33e5974b153c3a7df98dba51bbcd2/buildscripts/scripts/ffmpeg.sh#L29
```
	--disable-static --enable-shared --enable-gpl --enable-version3 \
```

https://github.com/mpv-android/mpv-android/blob/133a154ff7a33e5974b153c3a7df98dba51bbcd2/app/src/main/jni/Android.mk#L12
```
include $(CLEAR_VARS)
LOCAL_MODULE := libpostproc
LOCAL_SRC_FILES := $(PREFIX)/lib/$(LOCAL_MODULE).so
include $(PREBUILT_SHARED_LIBRARY)
```

31 Filters is added by this, full list here:
https://pastebin.com/xA2c6mJU

**Comment by sfan5** [comment]
Yeah we forgot to enable that.

**Comment by Ashyni** [comment]
Don't forget to edit https://github.com/mpv-android/mpv-android/blob/133a154ff7a33e5974b153c3a7df98dba51bbcd2/app/src/main/jni/Android.mk#L12
to add libpostproc.so or mpv-android will crash
```
09-30 15:59:34.958 27410 27410 W mpv     : Skipping copy of asset file (exists same size): subfont.ttf
09-30 15:59:34.958 27410 27410 W mpv     : Skipping copy of asset file (exists same size): cacert.pem
09-30 15:59:34.968 27410 27410 I HwPhoneWindow: updateLayoutParamsColor false mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=0, mNavBarShow=false, mIsFloating=false
09-30 15:59:34.970 27410 27410 I HwPhoneWindow: updateLayoutParamsColor true mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=ff000000, mNavBarShow=false, mIsFloating=false
09-30 15:59:35.030 27410 27410 I Window  : window add KeepScreenOnFlag for is.xyz.mpv
09-30 15:59:35.033  1793  6768 D HwRecentsTaskUtils: refreshToCache
09-30 15:59:35.033  1793  6768 D HwRecentsTaskUtils: searchFromDate
09-30 15:59:35.037  1677  2045 E HsmCoreServiceImpl: onTransact in code is: 103
09-30 15:59:35.037  1677  2045 I MediaProcessHandler: playingUids:
09-30 15:59:35.039 27410 27410 D AndroidRuntime: Shutting down VM
09-30 15:59:35.039  1793  6768 I RecentsTaskLoadPlan: to show tasks size is 1
09-30 15:59:35.040 27410 27410 E AndroidRuntime: FATAL EXCEPTION: main
09-30 15:59:35.040 27410 27410 E AndroidRuntime: Process: is.xyz.mpv, PID: 27410
09-30 15:59:35.040 27410 27410 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libpostproc.so" not found
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1672)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at is.xyz.mpv.MPVLib.<clinit>(MPVLib.java:19)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at is.xyz.mpv.MPVLib.create(Native Method)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at is.xyz.mpv.MPVView.initialize(MPVView.kt:19)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at is.xyz.mpv.MPVActivity.onCreate(MPVActivity.kt:185)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7458)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7448)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:112)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:216)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7625)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
09-30 15:59:35.040 27410 27410 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
09-30 15:59:35.043  1261  8973 W ActivityManager:   finishTopCrashedActivityLocked Force finishing activity is.xyz.mpv/.MPVActivity
09-30 15:59:35.045  1261  1280 I StatusBarDisable: setFlags what=0 which=1 pkg=Window{3ea94bd u0 is.xyz.mpv/is.xyz.mpv.MainActivity}
09-30 15:59:35.046  1261  8973 W ActivityManager:   finishTopCrashedActivityLocked non_home Force finishing activity is.xyz.mpv/.MainActivity
09-30 15:59:35.047  1261  8973 V ActivityManager: positionChild stackId=0 to top.
09-30 15:59:35.049  1261  1280 I StatusBarDisable: setFlags what=0 which=1 pkg=Window{3ea94bd u0 is.xyz.mpv/is.xyz.mpv.MainActivity}
09-30 15:59:35.050   668  2578 E iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
```
