### ISSUE TITLE
implementation in other project

### ISSUE THREAD

**Issue by ImOnii** [mpv-android/mpv-android#349]
Hey,
i have tried to implement mpv-android player in my project and i made changes on 
*jni_utils.h*
from:
```#define jni_func_name(name) Java_is_xyz_mpv_MPVLib_##name```
to:
```#define jni_func_name(name) Java_com_pckgname_mpv_MPVLib_##name```

And changes on *jni_utils.cpp*
from:
```mpv_MPVLib = FIND_CLASS("is/xyz/mpv/MPVLib");```
to:
```mpv_MPVLib = FIND_CLASS("com/pckgname/mpv/MPVLib");```

Changes made based on where MPVLib is located on project.
But when i try to play a video from the app i get this error:
```2021-01-13 22:05:41.307 29922-29922/com.pckgname E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pckgname, PID: 29922
    java.lang.UnsatisfiedLinkError: No implementation found for void com.pckgname.mpv.MPVLib.create(android.content.Context) (tried Java_com_pckgname_mpv_MPVLib_create and Java_com_pckgname_mpv_MPVLib_create__Landroid_content_Context_2)
        at com.pckgname.mpv.MPVLib.create(Native Method)
        at com.pckgname.mpv.MPVView.initialize(MPVView.kt:18)
        at com.pckgname.mpv.MPVActivity.onCreate(MPVActivity.kt:188)
        at android.app.Activity.performCreate(Activity.java:7028)
        at android.app.Activity.performCreate(Activity.java:7019)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2808)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2933)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1627)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:175)
        at android.app.ActivityThread.main(ActivityThread.java:6722)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)```

**Comment by sfan5** [comment]
No idea. The only suggestion I have is to ensure everything is recompiled correctly, you can also check if the symbols are present using `nm libplayer.so`.

**Comment by ImOnii** [comment]
@sfan5 thankyou, i had to recompile it and everything is working now.
