### ISSUE TITLE
App crash with java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by daymo** [mpv-android/mpv-android#39]
Choosing a file in FilePicker and the app crashed. 

Might be related to "Android NDK: ERROR:jni/Android.mk due to a missing file". Got this error while building with mpv-android/buildscripts:
 ```
Waf: Leaving directory `/home/Me/Development/mpv/buildscripts/deps/mpv/_build'
'install' finished successfully (1.483s)
~/Development/mpv/buildscripts
~/Development/mpv/buildscripts/mpv-android ~/Development/mpv/buildscripts
Android NDK: ERROR:jni/Android.mk:swresample: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /home/Me/Development/mpv/buildscripts/mpv-android/../prefix64/lib/libswresample.so exists  or that its path is correct   
make: Entering directory `/home/Me/Development/mpv/buildscripts/mpv-android/app/src/main'
/home/Me/Development/mpv/buildscripts/sdk/android-ndk-r13b/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
make: Leaving directory `/home/Me/Development/mpv/buildscripts/mpv-android/app/src/main'
```

See the stacktrace:

```
02-20 12:17:07.807 E/AndroidRuntime(3635): FATAL EXCEPTION: main
02-20 12:17:07.807 E/AndroidRuntime(3635): Process: is.xyz.mpv, PID: 3635
02-20 12:17:07.807 E/AndroidRuntime(3635): Theme: themes:{}
02-20 12:17:07.807 E/AndroidRuntime(3635): java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-support-annotations-25.1.0_bcea39d1289a51f94cfd8f353afcc2c2be3e1fb4-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-kotlin-stdlib-1.0.6_4ce30a787f9ca32462f5052441b98a158dcc9a8b-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-kotlin-runtime-1.0.6_8d571deea685efeadc867b17e02f41e87ad3cd89-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-com.nononsenseapps-filepicker-2.5.2_13fd7a768ca25b9671ad0bce9b638f2066e4ea8a-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-com.android.support-support-vector-drawable-25.1.0_020cc3810b7f9a7a55c6caecf3a9ca6c6cd3dfcf-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-com.android.support-support-v4-25.1.0_a771662e492c279cdd65ee869a4556fcb955779f-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-com.android.support-support-media-compat-25.1.0_a2695769ee3d5924e86a63708fbe19be5b7f69a4-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-com.android.support-support-fragment-25.1.0_59f5fc20bdf4289f7081574221363822c5babe7c-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-com.android.support-support-core-utils-25.1.0_3567ccf975c336bb207c83dcbcd186605a598bba-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-com.android.support-support-core-ui-25.1.0_5e8c34a385b94b898f3df6ce5182c5c5b34834e9-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-com.android.support-support-compat-25.1.0_256d136857f2dc06e1bdcaeeadcf0b7e5159c53e-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-com.android.support-recyclerview-v7-23.1.0_bb90b12adca34be113c43cd317fb475aaf345342-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-com.android.support-appcompat-v7-25.1.0_a60b170ad337714b4e121b4b33616fe3ab22235e-classes.dex", dex file "/data/data/is.xyz.mpv/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-25.1.0_72d280edfa1493afb14dc47362a98ee879e0e7e3-classes.dex"],nativeLibraryDirectories=[/data/app/is.xyz.mpv-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libmpv.so"
02-20 12:17:07.807 E/AndroidRuntime(3635): 	at java.lang.Runtime.loadLibrary(Runtime.java:367)
02-20 12:17:07.807 E/AndroidRuntime(3635): 	at java.lang.System.loadLibrary(System.java:1076)
02-20 12:17:07.807 E/AndroidRuntime(3635): 	at is.xyz.mpv.MPVLib.<clinit>(MPVLib.java:13)
02-20 12:17:07.807 E/AndroidRuntime(3635): 	at is.xyz.mpv.MPVView.initialize(MPVView.kt:19)
02-20 12:17:07.807 E/AndroidRuntime(3635): 	at is.xyz.mpv.MPVActivity.onCreate(MPVActivity.kt:116)
02-20 12:17:07.807 E/AndroidRuntime(3635): 	at android.app.Activity.performCreate(Activity.java:7125)
02-20 12:17:07.807 E/AndroidRuntime(3635): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
02-20 12:17:07.807 E/AndroidRuntime(3635): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2415)
02-20 12:17:07.807 E/AndroidRuntime(3635): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
02-20 12:17:07.807 E/AndroidRuntime(3635): 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
02-20 12:17:07.807 E/AndroidRuntime(3635): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
02-20 12:17:07.807 E/AndroidRuntime(3635): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-20 12:17:07.807 E/AndroidRuntime(3635): 	at android.os.Looper.loop(Looper.java
02-20 12:17:07.811 W/ActivityManager(653):   Force finishing activity is.xyz.mpv/.MPVActivity
02-20 12:17:07.817 W/ActivityManager(653):   Force finishing activity is.xyz.mpv/.MainActivity
02-20 12:17:07.896 I/Adreno-EGL(653): <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 06/22/16, f19e6a9, I9e7a63e7c4
02-20 12:17:07.897 I/OpenGLRenderer(653): Initialized EGL, version 1.4
02-20 12:17:08.317 W/ActivityManager(653): Activity pause timeout for ActivityRecord{53851e7 u0 is.xyz.mpv/.MPVActivity t828 f}
```

**Comment by sfan5** [comment]
https://github.com/mpv-android/buildscripts#build
