### ISSUE TITLE
Playlist file support

### ISSUE THREAD

**Issue by TealG** [mpv-android/mpv-android#57]
Opening a .pls file currently does not work -- would be quite a useful feature.

**Comment by sfan5** [comment]
Does the "normal" mpv support these? (Honestly I have never heard of those)
Mime type?

**Comment by TealG** [comment]
yes, mpv on desktop supports it.

MIME type: audio/x-scpls
https://en.wikipedia.org/wiki/PLS_(file_format)

**Comment by Veloxigami** [comment]
I was trying to enhance file picker system and also to workout on .pls feature but since it's all .kt, i'm having a little problem. In MPVLib.java it's showing error in the native methods "Cannot resolve  corresponding JNI function Java_is_xyz_mpv_MPVLib_"method name" and also this " Reports native method decelarations in Java where no corresponding JNI function is found in the project". Also, I'm not able to play any media when testing this app on my phone. It just crashes and the error log shows this



 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/is.xyz.mpv-1/base.apk"],nativeLibraryDirectories=[/data/app/is.xyz.mpv-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libmpv.so"
                                                                at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                at java.lang.System.loadLibrary(System.java:1076)
                                                                at is.xyz.mpv.MPVLib.<clinit>(MPVLib.java:16)
                                                                at is.xyz.mpv.MPVView.initialize(MPVView.kt:24)
                                                                at is.xyz.mpv.MPVActivity.onCreate(MPVActivity.kt:119)
                                                                at android.app.Activity.performCreate(Activity.java:6259)
                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:148)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by xyzz** [comment]
Use buildscripts: https://github.com/mpv-android/buildscripts to build mpv-android, not your IDE (I assume the jetbrains one). Also ignore the error it shows you.

**Comment by sfan5** [comment]
also note that playlists don't really work anyway (#67)

**Comment by Veloxigami** [comment]
Well, we can add feature for offline playlist at least, where user can add audio/video songs onto one playlist, won't that be useful?
Filepicker also should show only those directories which have compatible files in them i think.
