### ISSUE TITLE
Crashes upon launch (fresh install) on Android 13

### ISSUE THREAD

**Issue by DavidH-2022** [mpv-android/mpv-android#610]
### Important information

Android version: 13

mpv-android version: 2022-07-30-release

Which version of mpv-android introduced the problem (if known):
2022-07-30-release
### Description
The app crashes immediately after launch on Google Pixel 4a (5G) with Android 13 installed

### Log output
```
10-13 14:31:05.915 14379 14379 E AndroidRuntime: FATAL EXCEPTION: main
10-13 14:31:05.915 14379 14379 E AndroidRuntime: Process: is.xyz.mpv, PID: 14379
10-13 14:31:05.915 14379 14379 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {is.xyz.mpv/is.xyz.mpv.MainActivity}: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{81311a3 14379:is.xyz.mpv/u0a173} (pid=14379, uid=10173) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4803)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4836)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7898)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{81311a3 14379:is.xyz.mpv/u0a173} (pid=14379, uid=10173) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2995)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2978)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2920)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5224)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7033)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3420)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2526)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1203)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1151)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at is.xyz.filepicker.DocumentPickerFragment.isDir(DocumentPickerFragment.java:70)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at is.xyz.filepicker.DocumentPickerFragment.isTreeUsable(DocumentPickerFragment.java:53)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at is.xyz.mpv.MainScreenFragment.restoreChoice(MainScreenFragment.kt:119)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at is.xyz.mpv.MainScreenFragment.onResume(MainScreenFragment.kt:88)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performResume(Fragment.java:3039)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:607)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:306)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3086)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:273)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:458)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:447)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:240)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:8447)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4793)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	... 13 more
10-13 14:31:05.915 14379 14379 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.checkAssociationAndPermissionLocked(ContentProviderHelper.java:631)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:342)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:136)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:6476)
10-13 14:31:05.915 14379 14379 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2395)
10-13 14:31:05.915 14379 14379 E AndroidRuntime:
```

**Comment by sfan5** [comment]
Thanks for the detailed report. d7972d245b43b768e9271227b1239d1821d81d19 happens to already fix this.
Are you sure there weren't some settings carried over from an old install or backup? I don't see how this can happen otherwise.

**Comment by DavidH-2022** [comment]
Yes it is a fresh install on Android 13. I even tried to uninstall and reinstall but the error persists

**Comment by sfan5** [comment]
I just installed the last release APK in Android 13 inside the emulator, it does _not_ crash upon startup and the file manager also works as expected.
The changes described in the article you linked don't apply here because mpv-android targets Android 11 (API 30).

If this problem persists for you you can try deleting all app data from system settings.

**Comment by DavidH-2022** [comment]
oh thank you the problem is resolved right after clearing all app data
