### ISSUE TITLE
Opening mpv-android from another app causes crash (subtitles in intent)

### ISSUE THREAD

**Issue by IzanagisBurden** [mpv-android/mpv-android#980]
### Important information

Android version: 11

mpv-android version: 2024-08-20-release

Which version of mpv-android introduced the problem (if known): 2024-08-20-release

### Description

When using mpv-android as an external player for Jellyfin, trying to play a video file from Jellyfin results in a crash of both mpv-android and Jellyfin. Unsure whether this is a problem with mpv-android or Jellyfin, however the only thing that has changed is an update to mpv-android, This issue is not present on the previous version of mpv-android (2024-06-05 Build).

### Log output

Using the command from the bug report form, the only output is this:
```
08-22 14:18:30.553 14044 14044 V mpv     : Skipping copy of asset file (exists same size): subfont.ttf
08-22 14:18:30.553 14044 14044 V mpv     : Skipping copy of asset file (exists same size): cacert.pem
```
However, I think this part from the unfiltered log is more relevant:
```
08-22 14:31:24.323  1073  2864 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=http://192.168.0.140:8096/... typ=video/* cmp=is.xyz.mpv/.MPVActivity (has extras)} from uid 10186
08-22 14:31:24.348   493   493 D Zygote  : Forked child process 14756
08-22 14:31:24.360  1073  1206 I ActivityManager: Start proc 14756:is.xyz.mpv/u0a243 for pre-top-activity {is.xyz.mpv/is.xyz.mpv.MPVActivity}
08-22 14:31:24.416 14756 14756 W is.xyz.mpv: JIT profile information will not be recorded: profile file does not exist.
08-22 14:31:24.417 14756 14756 W is.xyz.mpv: JIT profile information will not be recorded: profile file does not exist.
08-22 14:31:24.425 14756 14756 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-22 14:31:24.425 14756 14756 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-22 14:31:24.454 14756 14756 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
08-22 14:31:24.483 14756 14756 V mpv     : Skipping copy of asset file (exists same size): subfont.ttf
08-22 14:31:24.483 14756 14756 V mpv     : Skipping copy of asset file (exists same size): cacert.pem
08-22 14:31:24.541 14756 14756 D AndroidRuntime: Shutting down VM
08-22 14:31:24.542 14756 14756 E AndroidRuntime: FATAL EXCEPTION: main
08-22 14:31:24.542 14756 14756 E AndroidRuntime: Process: is.xyz.mpv, PID: 14756
08-22 14:31:24.542 14756 14756 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{is.xyz.mpv/is.xyz.mpv.MPVActivity}: java.lang.ClassCastException: android.os.Parcelable[] cannot be cast to android.net.Uri[]
08-22 14:31:24.542 14756 14756 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
08-22 14:31:24.542 14756 14756 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
08-22 14:31:24.542 14756 14756 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
08-22 14:31:24.542 14756 14756 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-22 14:31:24.542 14756 14756 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-22 14:31:24.542 14756 14756 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
08-22 14:31:24.542 14756 14756 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-22 14:31:24.542 14756 14756 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
08-22 14:31:24.542 14756 14756 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7664)
08-22 14:31:24.542 14756 14756 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-22 14:31:24.542 14756 14756 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
08-22 14:31:24.542 14756 14756 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
08-22 14:31:24.542 14756 14756 E AndroidRuntime: Caused by: java.lang.ClassCastException: android.os.Parcelable[] cannot be cast to android.net.Uri[]
08-22 14:31:24.542 14756 14756 E AndroidRuntime:        at is.xyz.mpv.MPVActivity.parseIntentExtras(MPVActivity.kt:999)
08-22 14:31:24.542 14756 14756 E AndroidRuntime:        at is.xyz.mpv.MPVActivity.onCreate(MPVActivity.kt:305)
08-22 14:31:24.542 14756 14756 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7994)
08-22 14:31:24.542 14756 14756 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7978)
08-22 14:31:24.542 14756 14756 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
08-22 14:31:24.542 14756 14756 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
08-22 14:31:24.542 14756 14756 E AndroidRuntime:        ... 11 more
08-22 14:31:24.545  1073  7257 W ActivityTaskManager:   Force finishing activity is.xyz.mpv/.MPVActivity
08-22 14:31:24.548  1073  7257 W ActivityTaskManager:   Force finishing activity org.jellyfin.mobile/.MainActivity
```

**Comment by giulianoriccio** [comment]
Same issue here with Android 13

**Comment by sfan5** [comment]
culprit: edd9b76f91137f69da6b46081fe33b01e903d7c2

it's weird because I tested this with the example code in our documentation

can you locate the code inside the jellyfin that calls mpv?
or maybe provide a detailed dump of the intent mpv receives (not sure how)?

**Comment by fatSquirrel42** [comment]
I just wanted to let you know that the error also occurs with the Android TV app from Jellyfin. [jellyfin-androidtv](https://github.com/jellyfin/jellyfin-androidtv)
Unfortunately, I can't make out where in the code the external player is called.
